var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/portfolio/[id]/edit/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p19txy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1-w3xlf.js")
R.c("server/chunks/ssr/[root-of-the-server]__1d72as7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1kg6blg._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_1iylvrn._.js")
R.c("server/chunks/ssr/src_0-u3tf7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_0p6twgf._.js")
R.c("server/chunks/ssr/_1tdou1s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0b4ex_-._.js")
R.c("server/chunks/ssr/src_lib_supabase_ts_1-552tg._.js")
R.c("server/chunks/ssr/_0lf9nwz._.js")
R.m(65500)
module.exports=R.m(65500).exports
