var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/main/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__13g72hx._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_05i_eno.js")
R.c("server/chunks/ssr/[root-of-the-server]__1d72as7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1kg6blg._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_1iylvrn._.js")
R.c("server/chunks/ssr/src_0-u3tf7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_0p6twgf._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_main_new_page_actions_0sw7s72.js")
R.m(61039)
module.exports=R.m(61039).exports
